### 1. Registrar un nuevo usuario de prueba
# Usamos una variable de timestamp para generar un email único cada vez que ejecutamos el test
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "admin@labotica.com",
  "password": "admin",
  "name": "admin"
}

### SEPARADOR ###

### 2. Iniciar sesión con el usuario recién creado
# Esta petición fallará si la de registro no se ha ejecutado antes
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@labotica.com",
  "password": "admin"
}

> {%
    // Este script se ejecuta después de la petición.
    // Captura el token de la respuesta y lo guarda en una variable global
    // llamada 'auth_token' para poder usarlo en las siguientes peticiones.
    client.global.set("auth_token", response.body.token);
%}

### SEPARADOR ###

### 3. Probar una ruta protegida (ej. obtener el carrito)
# Esta petición usará el token que guardamos en el paso anterior.
# Si funciona, significa que el login y la generación de JWT también son correctos.
GET http://localhost:8080/carrito
Authorization: Bearer {{auth_token}}