ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080
database:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/catalogo_db"
  user: "ktalogdb"
  password: "Nx.695"
  maxPoolSize: 10
jwt:
  issuer: "http://0.0.0.0:8080"
  audience: "catalogo-app-users"
  realm: "Catalogo App"